export const data = [
  {
    model: "Redmi 11",
    address: "Av. Corrientes 3320",
    date: "22/12/23",
    color: "Silver",
    type: "phone",
  },
  {
    model: "Samsung Galaxy S9",
    address: "Güiraldes 1428, Villa Maipu",
    date: "22/12/23",
    color: "Black",
    type: "phone",
  },
  // {
  //   model: "iPhone X",
  //   address: "Prevere Antoni Lliteres 1",
  //   date: "15/11/23",
  //   color: "Silver",
  //   type: "phone",
  // },
  // {
  //   model: "Google Pixel 3",
  //   address: "Estrada 1171, Villa Maipu",
  //   date: "03/01/24",
  //   color: "White",
  //   type: "phone",
  // },
  // {
  //   model: "LG G7 ThinQ",
  //   address: "Av. 9 de julio 1240",
  //   date: "15/01/24",
  //   color: "Blue",
  //   type: "phone",
  // },
  // {
  //   model: "Motorola Moto G6",
  //   address: "654 Maple Street",
  //   date: "1580515200",
  //   color: "Gold",
  //   type: "phone",
  // },
  // {
  //   model: "OnePlus 6T",
  //   address: "987 Cedar Street",
  //   date: "18/01/24",
  //   color: "Red",
  //   type: "phone",
  // },
  // {
  //   model: "Sony Xperia XZ2",
  //   address: "1590 Birch Street",
  //   date: "19/01/24",
  //   color: "Green",
  //   type: "phone",
  // },
  // {
  //   model: "Huawei P30 Pro",
  //   address: "753 Walnut Street",
  //   date: "20/01/24",
  //   color: "Purple",
  //   type: "phone",
  // },
  // {
  //   model: "Nokia 9 PureView",
  //   address: "9510 Ash Street",
  //   date: "29/01/24",
  //   color: "Pink",
  //   type: "phone",
  // },
];
